import RootLayout from "../layout";
import Home from "../page";

export const metadata = {
  title: "About Us",
  description: "Generated by create next app",
};

export default function Page() {
  
  return (
    <>
      <RootLayout>
        <Home>
        <h1>Welcome to page!</h1>
        </Home>
      </RootLayout>
    </>
  );
}